- name: "Format volume and attach to /dev/xvdh/"
  hosts: all
  become: true

  tasks:
    - name: format the EBS filesystem
      filesystem:
        fstype: ext4
        dev: /dev/xvdh

    - name: configure the EBS volume mount point
      mount:
        path: /data
        src: /dev/xvdh
        fstype: ext4
        state: present

    - name: mount the EBS volume
      mount:
        path: /data
        src: /dev/xvdh
        fstype: ext4
        state: mounted

    - name: set owner of /data
      file:
        path: /data
        owner: ubuntu
        group: ubuntu
